name: api_test
description: Learning how to create an API with GET, POST, PUT, DELETE.

publish_to:
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  http: ^1.1.0

flutter:
  uses-material-design: true